In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv("../data/raw/train.csv")

In [4]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [5]:
df.shape

(1460, 81)

In [6]:
df["PoolQC"].isna().sum()

np.int64(1453)

In [7]:
df["PoolArea"].value_counts().head()

PoolArea
0      1453
512       1
648       1
576       1
555       1
Name: count, dtype: int64

In [8]:
(df["PoolQC"].isna().sum()/len(df))*100

np.float64(99.52054794520548)

In [9]:
missing=df.isna().sum().sort_values(ascending=False)
missing[missing > 0]

PoolQC          1453
MiscFeature     1406
Alley           1369
Fence           1179
MasVnrType       872
FireplaceQu      690
LotFrontage      259
GarageQual        81
GarageFinish      81
GarageType        81
GarageYrBlt       81
GarageCond        81
BsmtFinType2      38
BsmtExposure      38
BsmtCond          37
BsmtQual          37
BsmtFinType1      37
MasVnrArea         8
Electrical         1
dtype: int64

In [10]:
missing_percentage=(df.isna().sum()/len(df)*100).sort_values(ascending=False)
missing_percentage[missing_percentage > 0]

PoolQC          99.520548
MiscFeature     96.301370
Alley           93.767123
Fence           80.753425
MasVnrType      59.726027
FireplaceQu     47.260274
LotFrontage     17.739726
GarageQual       5.547945
GarageFinish     5.547945
GarageType       5.547945
GarageYrBlt      5.547945
GarageCond       5.547945
BsmtFinType2     2.602740
BsmtExposure     2.602740
BsmtCond         2.534247
BsmtQual         2.534247
BsmtFinType1     2.534247
MasVnrArea       0.547945
Electrical       0.068493
dtype: float64

In [11]:
df[df["GarageType"].isna()][["GarageType","GarageYrBlt","GarageQual","GarageFinish","GarageCars",
                            "GarageArea","GarageCond"]].head()

,GarageType,GarageYrBlt,GarageQual,GarageFinish,GarageCars,GarageArea,GarageCond
39,NaN,NaN,NaN,NaN,0,0,NaN
48,NaN,NaN,NaN,NaN,0,0,NaN
78,NaN,NaN,NaN,NaN,0,0,NaN
88,NaN,NaN,NaN,NaN,0,0,NaN
89,NaN,NaN,NaN,NaN,0,0,NaN

In [12]:
df[df["GarageType"].isna()][["GarageCars","GarageArea"]].value_counts()

GarageCars  GarageArea
0           0             81
Name: count, dtype: int64

In [13]:
df[df["BsmtQual"].isna()][["BsmtQual", "BsmtCond", "BsmtExposure","BsmtFinType1", "BsmtFinType2",
                            "TotalBsmtSF", "BsmtFinSF1", "BsmtFinSF2", "BsmtUnfSF"]].head(10)

,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,TotalBsmtSF,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF
17,NaN,NaN,NaN,NaN,NaN,0,0,0,0
39,NaN,NaN,NaN,NaN,NaN,0,0,0,0
90,NaN,NaN,NaN,NaN,NaN,0,0,0,0
102,NaN,NaN,NaN,NaN,NaN,0,0,0,0
156,NaN,NaN,NaN,NaN,NaN,0,0,0,0
182,NaN,NaN,NaN,NaN,NaN,0,0,0,0
259,NaN,NaN,NaN,NaN,NaN,0,0,0,0
342,NaN,NaN,NaN,NaN,NaN,0,0,0,0
362,NaN,NaN,NaN,NaN,NaN,0,0,0,0
371,NaN,NaN,NaN,NaN,NaN,0,0,0,0

In [14]:
df[df["BsmtQual"].isna()][["TotalBsmtSF", "BsmtFinSF1", "BsmtFinSF2", "BsmtUnfSF"]].value_counts()

TotalBsmtSF  BsmtFinSF1  BsmtFinSF2  BsmtUnfSF
0            0           0           0            37
Name: count, dtype: int64

In [15]:
df[df["BsmtFinType2"].isna()][["BsmtQual", "BsmtCond", "BsmtExposure","BsmtFinType1", "BsmtFinType2",
                                "TotalBsmtSF", "BsmtFinSF1", "BsmtFinSF2", "BsmtUnfSF"]]

,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,TotalBsmtSF,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF
17,NaN,NaN,NaN,NaN,NaN,0,0,0,0
39,NaN,NaN,NaN,NaN,NaN,0,0,0,0
90,NaN,NaN,NaN,NaN,NaN,0,0,0,0
102,NaN,NaN,NaN,NaN,NaN,0,0,0,0
156,NaN,NaN,NaN,NaN,NaN,0,0,0,0
182,NaN,NaN,NaN,NaN,NaN,0,0,0,0
259,NaN,NaN,NaN,NaN,NaN,0,0,0,0
332,Gd,TA,No,GLQ,NaN,3206,1124,479,1603
342,NaN,NaN,NaN,NaN,NaN,0,0,0,0
362,NaN,NaN,NaN,NaN,NaN,0,0,0,0
371,NaN,NaN,NaN,NaN,NaN,0,0,0,0
392,NaN,NaN,NaN,NaN,NaN,0,0,0,0
520,NaN,NaN,NaN,NaN,NaN,0,0,0,0
532,NaN,NaN,NaN,NaN,NaN,0,0,0,0
533,NaN,NaN,NaN,NaN,NaN,0,0,0,0
553,NaN,NaN,NaN,NaN,NaN,0,0,0,0
646,NaN,NaN,NaN,NaN,NaN,0,0,0,0
705,NaN,NaN,NaN,NaN,NaN,0,0,0,0
736,NaN,NaN,NaN,NaN,NaN,0,0,0,0
749,NaN,NaN,NaN,NaN,NaN,0,0,0,0
778,NaN,NaN,NaN,NaN,NaN,0,0,0,0
868,NaN,NaN,NaN,NaN,NaN,0,0,0,0
894,NaN,NaN,NaN,NaN,NaN,0,0,0,0
897,NaN,NaN,NaN,NaN,NaN,0,0,0,0
984,NaN,NaN,NaN,NaN,NaN,0,0,0,0
1000,NaN,NaN,NaN,NaN,NaN,0,0,0,0
1011,NaN,NaN,NaN,NaN,NaN,0,0,0,0
1035,NaN,NaN,NaN,NaN,NaN,0,0,0,0
1045,NaN,NaN,NaN,NaN,NaN,0,0,0,0
1048,NaN,NaN,NaN,NaN,NaN,0,0,0,0
1049,NaN,NaN,NaN,NaN,NaN,0,0,0,0
1090,NaN,NaN,NaN,NaN,NaN,0,0,0,0
1179,NaN,NaN,NaN,NaN,NaN,0,0,0,0
1216,NaN,NaN,NaN,NaN,NaN,0,0,0,0
1218,NaN,NaN,NaN,NaN,NaN,0,0,0,0
1232,NaN,NaN,NaN,NaN,NaN,0,0,0,0
1321,NaN,NaN,NaN,NaN,NaN,0,0,0,0
1412,NaN,NaN,NaN,NaN,NaN,0,0,0,0

In [16]:
df[df["BsmtFinType2"].isna() & (df["TotalBsmtSF"]>0)][["Id","BsmtQual","BsmtFinType1","BsmtFinType2",
                                                      "TotalBsmtSF","BsmtFinSF1","BsmtFinSF2","BsmtUnfSF"]]

,Id,BsmtQual,BsmtFinType1,BsmtFinType2,TotalBsmtSF,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF
332,333,Gd,GLQ,NaN,3206,1124,479,1603

In [17]:
df[df["BsmtFinType2"].isna() & (df["TotalBsmtSF"]>0)].shape

(1, 81)

In [18]:
df[df["MasVnrType"].isna()][["MasVnrType", "MasVnrArea"]].head(10)

   MasVnrType  MasVnrArea
1         NaN         0.0
3         NaN         0.0
5         NaN         0.0
8         NaN         0.0
9         NaN         0.0
10        NaN         0.0
12        NaN         0.0
15        NaN         0.0
17        NaN         0.0
18        NaN         0.0

In [19]:
df[df["MasVnrArea"].isna()][["MasVnrType", "MasVnrArea"]]

     MasVnrType  MasVnrArea
234         NaN         NaN
529         NaN         NaN
650         NaN         NaN
936         NaN         NaN
973         NaN         NaN
977         NaN         NaN
1243        NaN         NaN
1278        NaN         NaN

In [20]:
df.groupby("MasVnrType",dropna=False)["MasVnrArea"].agg(["count","min","max"])

            count   min     max
MasVnrType
BrkCmn         15  41.0   621.0
BrkFace       445   0.0  1600.0
Stone         128   0.0   860.0
NaN           864   0.0   344.0

In [21]:
df[df["MasVnrType"].isna() & (df["MasVnrArea"] > 0)][["Id", "MasVnrType", "MasVnrArea"]]

        Id MasVnrType  MasVnrArea
624    625        NaN       288.0
773    774        NaN         1.0
1230  1231        NaN         1.0
1300  1301        NaN       344.0
1334  1335        NaN       312.0

In [22]:
df[df["MasVnrType"].isna() & (df["MasVnrArea"] > 0)].shape

(5, 81)

In [23]:
df[df["MasVnrArea"].isna()][["Id","MasVnrType","MasVnrArea","OverallQual","YearBuilt",
                            "Exterior1st","Exterior2nd"]]

,Id,MasVnrType,MasVnrArea,OverallQual,YearBuilt,Exterior1st,Exterior2nd
234,235,NaN,NaN,6,2002,VinylSd,VinylSd
529,530,NaN,NaN,6,1957,Wd Sdng,Stone
650,651,NaN,NaN,7,2007,CemntBd,CmentBd
936,937,NaN,NaN,7,2003,VinylSd,VinylSd
973,974,NaN,NaN,7,2007,CemntBd,CmentBd
977,978,NaN,NaN,7,2006,VinylSd,VinylSd
1243,1244,NaN,NaN,10,2006,VinylSd,VinylSd
1278,1279,NaN,NaN,8,2002,VinylSd,VinylSd

In [24]:
df_raw_check = pd.read_csv("../data/raw/train.csv",keep_default_na=False)

In [25]:
df_raw_check["MasVnrType"].value_counts()

MasVnrType
None       864
BrkFace    445
Stone      128
BrkCmn      15
NA           8
Name: count, dtype: int64

In [26]:
df_raw_check["MasVnrType"].value_counts(dropna=False)

MasVnrType
None       864
BrkFace    445
Stone      128
BrkCmn      15
NA           8
Name: count, dtype: int64

In [27]:
df_raw_check["MasVnrArea"].isna().sum()

np.int64(0)

In [28]:
df_raw_check[df_raw_check["MasVnrType"] == "NA"][["Id", "MasVnrType", "MasVnrArea"]]

        Id MasVnrType MasVnrArea
234    235         NA         NA
529    530         NA         NA
650    651         NA         NA
936    937         NA         NA
973    974         NA         NA
977    978         NA         NA
1243  1244         NA         NA
1278  1279         NA         NA

In [29]:
df_raw_check[df_raw_check["MasVnrType"] == "NA"]["MasVnrArea"]

234     NA
529     NA
650     NA
936     NA
973     NA
977     NA
1243    NA
1278    NA
Name: MasVnrArea, dtype: str

In [30]:
df_raw_check.dtypes[["MasVnrType", "MasVnrArea"]]

MasVnrType    str
MasVnrArea    str
dtype: object

In [31]:
df[df["LotFrontage"].isna()][["Id", "LotFrontage", "Neighborhood", "LotArea"]].head(10)

    Id  LotFrontage Neighborhood  LotArea
7    8          NaN       NWAmes    10382
12  13          NaN       Sawyer    12968
14  15          NaN        NAmes    10920
16  17          NaN        NAmes    11241
24  25          NaN       Sawyer     8246
31  32          NaN       Sawyer     8544
42  43          NaN      SawyerW     9180
43  44          NaN      CollgCr     9200
50  51          NaN      Gilbert    13869
64  65          NaN      CollgCr     9375

In [32]:
df.groupby("Neighborhood")["LotFrontage"].agg(["count", "mean", "median"]).sort_values("median")

              count       mean  median
Neighborhood
BrDale           16  21.562500    21.0
MeadowV          15  27.800000    21.0
NPkVill           7  32.285714    24.0
Blueste           2  24.000000    24.0
Blmngtn          14  47.142857    43.0
BrkSide          51  57.509804    52.0
IDOTRR           34  62.500000    60.0
OldTown         109  62.788991    60.0
SWISU            23  58.913043    60.0
StoneBr          20  62.700000    61.5
Gilbert          49  79.877551    65.0
Edwards          92  68.217391    65.5
SawyerW          50  71.500000    66.5
Veenker           7  59.714286    68.0
CollgCr         126  71.682540    70.0
Sawyer           48  74.437500    71.0
NAmes           186  76.462366    73.0
Mitchel          36  70.083333    73.0
Somerst          78  64.666667    73.5
Crawfor          41  71.804878    74.0
ClearCr          13  83.461538    80.0
NWAmes           45  81.288889    80.0
Timber           30  80.133333    85.0
NridgHt          76  81.881579    88.5
NoRidge          33  91.878788    91.0

In [33]:
lotfrontage_missing = (df[df["LotFrontage"].isna()].groupby("Neighborhood").size().sort_values(ascending=False))
lotfrontage_missing

Neighborhood
NAmes      39
Gilbert    30
NWAmes     28
Sawyer     26
CollgCr    24
ClearCr    15
Mitchel    13
Crawfor    10
SawyerW     9
Edwards     8
Timber      8
Somerst     8
NoRidge     8
BrkSide     7
StoneBr     5
Veenker     4
OldTown     4
Blmngtn     3
IDOTRR      3
MeadowV     2
NPkVill     2
SWISU       2
NridgHt     1
dtype: int64

In [34]:
df.groupby("Neighborhood")["LotFrontage"].agg(["count", "median"]).sort_values("median")

              count  median
Neighborhood
BrDale           16    21.0
MeadowV          15    21.0
NPkVill           7    24.0
Blueste           2    24.0
Blmngtn          14    43.0
BrkSide          51    52.0
IDOTRR           34    60.0
OldTown         109    60.0
SWISU            23    60.0
StoneBr          20    61.5
Gilbert          49    65.0
Edwards          92    65.5
SawyerW          50    66.5
Veenker           7    68.0
CollgCr         126    70.0
Sawyer           48    71.0
NAmes           186    73.0
Mitchel          36    73.0
Somerst          78    73.5
Crawfor          41    74.0
ClearCr          13    80.0
NWAmes           45    80.0
Timber           30    85.0
NridgHt          76    88.5
NoRidge          33    91.0

In [36]:
neighborhood_stats=(df.groupby("Neighborhood")["LotFrontage"].agg(["count","median"]).sort_values("count"))
neighborhood_stats

              count  median
Neighborhood
Blueste           2    24.0
NPkVill           7    24.0
Veenker           7    68.0
ClearCr          13    80.0
Blmngtn          14    43.0
MeadowV          15    21.0
BrDale           16    21.0
StoneBr          20    61.5
SWISU            23    60.0
Timber           30    85.0
NoRidge          33    91.0
IDOTRR           34    60.0
Mitchel          36    73.0
Crawfor          41    74.0
NWAmes           45    80.0
Sawyer           48    71.0
Gilbert          49    65.0
SawyerW          50    66.5
BrkSide          51    52.0
NridgHt          76    88.5
Somerst          78    73.5
Edwards          92    65.5
OldTown         109    60.0
CollgCr         126    70.0
NAmes           186    73.0

In [38]:
print("Groups with fewer than 5 observations:",(neighborhood_stats["count"]<5).sum())
print("Groups with fewer than 10 observations:",(neighborhood_stats["count"]<10).sum())
print("Groups with fewer than 20 observations:",(neighborhood_stats["count"]<20).sum())

Groups with fewer than 5 observations: 1
Groups with fewer than 10 observations: 3
Groups with fewer than 20 observations: 7